defines QNX implementation for rcutils_get_platform_library_name
ros2/rcutils pull request #287
Opened 2020-08-27 17:56 UTC by asobhy-qnx

Fixes #286

2020-08-28 08:26 UTC, ahcorde approved these changes

2020-08-28 08:27 UTC, ahcorde commented on src/shared_library.c
> +#if defined(__linux__) || defined(__QNXNTO__)
```suggestion
#if defined(__linux__) || defined(__QNXNTO__)
```

2020-08-28 08:27 UTC, ahcorde requested changes
Please check the linters (uncrustify)

2020-08-28 13:58 UTC, ahcorde approved these changes

2020-08-31 15:04 UTC, ahcorde commented
Testing up-to rcutils

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12141)](http://ci.ros2.org/job/ci_linux/12141/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7131)](http://ci.ros2.org/job/ci_linux-aarch64/7131/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9884)](http://ci.ros2.org/job/ci_osx/9884/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12040)](http://ci.ros2.org/job/ci_windows/12040/)

2020-09-02 14:21 UTC, merged

2020-10-22 20:07 UTC, asobhy-qnx commented
@dirk-thomas can this be back ported to foxy and dashing

2020-11-10 20:43 UTC, jacobperron commented
Foxy backport is here: https://github.com/ros2/rcutils/pull/309

I don't believe this change is applicable to Dashing since there is no `shared_library.c`.