Stop double-defining structs.
ros2/rcutils pull request #333
Opened 2021-03-12 14:41 UTC by clalancette

Currently we use something like:

typedef struct foo_t
{
} foo_t;

But that actually double-defines the `foo_t` symbol
(at least, according to Doxygen).  Instead, use the
more traditional:

typedef struct foo
{
} foo_t;

This is slightly controversial in that it is an API break;
any code that was using `struct foo_t` before will now fail
to compile (anything that was just using `foo_t` will be fine).

However, this should mostly affect low-level libraries
like client libraries and the such, so the scale of breakage
here should be low.

Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

2021-03-12 15:09 UTC, clalancette commented
CI (everything, just to ensure there is no higher-level breakage):
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13926)](http://ci.ros2.org/job/ci_linux/13926/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8769)](http://ci.ros2.org/job/ci_linux-aarch64/8769/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11630)](http://ci.ros2.org/job/ci_osx/11630/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14012)](http://ci.ros2.org/job/ci_windows/14012/)

2021-03-12 23:02 UTC, ahcorde approved these changes

2021-03-13 02:41 UTC, fujitatomoya approved these changes
lgtm

2021-08-04 23:59 UTC, wjwwood requested changes
I would actually prefer to see this pattern:

```c
typedef struct rcutils_foo_s {
  // ...
} rcutils_foo_t;
```

My reasons for this:

- we already have code like `rcutils_foo_t rcutils_foo = ...;`
- other users (outside our code base) could be using `rcutils_foo` (without the `_t`) causing a collision, but I think it is much less likely anyone is using `rcutils_foo_s`
- having some suffix helps denote that it may be a complex type
- though it is discouraged to use `_t` in your projects, the reasoning is that `POSIX` may arbitrarily add new `<type>_t` types, but since we namespace 100% of our C symbols with `<package_name>_`, that's not a problem
- when using auto-complete seeing `foo_t` and `foo_s` indicates to me (without knowing the code base) which is the struct and which is the typedef, i.e. with `foo` and `foo_t` it could just as easily be `struct foo_t` as `struct foo` in my opinion

Thoughts?

---

If others agree, then I can update this pull request and add some documentation to our contributing/style guides.

2021-08-05 00:03 UTC, wjwwood commented
> we already have code like `rcutils_foo_t rcutils_foo = ...;`

I should clarify I think this is the case if we expand this pattern to other packages like `rmw` and `rcl`, though I don't think we have any instances of it for `rcutils`.

2021-08-05 13:54 UTC, clalancette commented
> Thoughts?

I honestly don't have a strong opinion either way, so I'll go ahead and rebase this and change it to `_s` everywhere.

2021-08-05 14:19 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14986)](http://ci.ros2.org/job/ci_linux/14986/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9727)](http://ci.ros2.org/job/ci_linux-aarch64/9727/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12672)](http://ci.ros2.org/job/ci_osx/12672/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15150)](http://ci.ros2.org/job/ci_windows/15150/)

2021-08-06 19:40 UTC, wjwwood approved these changes

2021-08-06 19:46 UTC, wjwwood commented
Rerunning CI since https://github.com/ros2/system_tests/pull/481 and https://github.com/ros2/rcl_interfaces/pull/125 were merged:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=15003)](http://ci.ros2.org/job/ci_linux/15003/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9742)](http://ci.ros2.org/job/ci_linux-aarch64/9742/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12690)](http://ci.ros2.org/job/ci_osx/12690/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=15165)](http://ci.ros2.org/job/ci_windows/15165/)

2021-08-08 12:59 UTC, clalancette commented
The failures in Windows were also in the nightlies.  I'm going to go ahead and merge this, thanks for the reviews!

2021-08-08 12:59 UTC, merged

2021-09-20 20:52 UTC, ros-discourse commented
This pull request has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/ros-2-tsc-meeting-minutes-2021-9-16/22372/1