Restrict overmatching MACH ifdef to only trigger on OSX and Mach
ros2/rcutils pull request #386
Opened 2022-09-21 06:23 UTC by Zopolis4

As said on line 43, this check is only intended for OSX.
```
 // Assume clock_get_time is available on OS X.
```

Hurd uses a different version of Mach that does not have `mach/clock.h`.
https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
```
#ifdef __MACH__
Some applications put Apple Darwin-specific code inside #ifdef __MACH__ guards. Such guard is clearly not enough, since not only Apple uses Mach as a kernel. This should be replaced by #if defined(__MACH__) && defined(__APPLE__)
```

Signed-off-by: Maximilian Downey Twiss <creatorsmithmdt@gmail.com>

2022-09-21 12:39 UTC, clalancette requested changes
One fix inline, then this will be ready for CI.

2022-09-21 12:39 UTC, clalancette commented on src/time_unix.c
> +#if !defined(__MACH__)  && !defined(__APPLE__)   // Assume clock_get_time is available on OS X.
The linter is unhappy here.

```suggestion
#if !defined(__MACH__) && !defined(__APPLE__)   // Assume clock_get_time is available on OS X.
```

2022-09-22 13:15 UTC, clalancette approved these changes

2022-09-22 13:16 UTC, clalancette commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17356)](http://ci.ros2.org/job/ci_linux/17356/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11891)](http://ci.ros2.org/job/ci_linux-aarch64/11891/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17851)](http://ci.ros2.org/job/ci_windows/17851/)

2022-09-22 14:13 UTC, Zopolis4 commented
This doesn't touch windows at all, so not sure what's going on there.

2022-09-22 14:50 UTC, clalancette commented
> This doesn't touch windows at all, so not sure what's going on there.

We've been having some instability with the Windows workers, it looks like we ran into it.  I've kicked off a new job.

2022-09-23 14:32 UTC, clalancette commented
The single failing test on Windows has nothing to do with this, so I'll go ahead and merge it.

2022-09-23 14:32 UTC, merged