load dll built by MINGW with lib prefix
ros2/rcutils pull request #470
Opened 2024-06-12 06:57 UTC by felixf4xu

Hi,

When a WIN32 shared dll project is built by **MINGW**, the .dll file name will have a prefix of `lib` by cmake default setting, for example, "**lib**rmw_cyclonedds_cpp.dll".

This PR add the support for the case, load the rmw middleware with a **lib** prefix if it's built by MINGW.

2024-06-12 08:33 UTC, ahcorde approved these changes
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21254)](http://ci.ros2.org/job/ci_linux/21254/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15574)](http://ci.ros2.org/job/ci_linux-aarch64/15574/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=747)](http://ci.ros2.org/job/ci_linux-rhel/747/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21978)](http://ci.ros2.org/job/ci_windows/21978/)

2024-06-12 17:00 UTC, fujitatomoya requested changes

2024-06-12 17:00 UTC, fujitatomoya commented on src/shared_library.c
> +#endif // __MINGW64__
nit detected by rpr job https://ci.ros2.org/job/ci_linux/21254/testReport/(root)/projectroot/cpplint/

```suggestion
#endif  // __MINGW64__
```

```shell
/home/jenkins-agent/workspace/ci_linux/ws/src/ros2/rcutils/src/shared_library.c:346:  At least two spaces is best between code and comments  [whitespace/comments] [2]
```

2024-06-14 15:15 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21268)](http://ci.ros2.org/job/ci_linux/21268/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15587)](http://ci.ros2.org/job/ci_linux-aarch64/15587/)
* Linux-rhel [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-rhel&build=763)](http://ci.ros2.org/job/ci_linux-rhel/763/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21994)](http://ci.ros2.org/job/ci_windows/21994/)

2024-06-17 08:24 UTC, merged